### ISSUE TITLE
Possible linker issue on Ubuntu 18.04 - Undefined Reference

### ISSUE THREAD

**Issue by magicbycalvin** [MattiaMontanari/openGJK#11]
I followed the installation instructions (create a new folder, call cmake followed by make) but ran into the following error:
```
../lib/libopenGJKlib.a(openGJK.c.o): In function `S2D':
openGJK.c:(.text+0x116): undefined reference to `pow'
openGJK.c:(.text+0x17c3): undefined reference to `sqrt'
../lib/libopenGJKlib.a(openGJK.c.o): In function `gjk':
openGJK.c:(.text+0x3d1b): undefined reference to `sqrt'
collect2: error: ld returned 1 exit status
example1_c/CMakeFiles/demo.dir/build.make:95: recipe for target 'example1_c/demo' failed
make[2]: *** [example1_c/demo] Error 1
CMakeFiles/Makefile2:140: recipe for target 'example1_c/CMakeFiles/demo.dir/all' failed
make[1]: *** [example1_c/CMakeFiles/demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I am not very experienced with cmake and make so there is a chance that I have done something wrong. I looked in the CMakeLists.txt file and noticed that you do include the `-lm` flag which should properly link the math library which suggests that it should work. Perhaps there is a load order issue?

In the meantime, I managed to temporarily fix it by copying `openGJK.c` to `openGJK/example1_c` and `openGJK.h` to `openGJK/example1_c/openGJK` and then running `gcc main.c openGJK.c -o openGJK.bin -lm`.

Please let me know if I am missing anything. Thanks!

**Comment by MattiaMontanari** [comment]
I think you're doing all OK and the problem is in my setting. However, try to work on the development branch. That should work OK and you can refer to the docs here https://mmontanari.gitlab.io/opengjk_3d/

I apologise for leaving the master branch in this state.. I should merge soon..
________________________________

**Comment by magicbycalvin** [comment]
No worries, thanks for the quick response!

**Comment by MattiaMontanari** [comment]
Just checking, did that work?

**Comment by magicbycalvin** [comment]
Just tested the `dev` branch and it worked out great!
On a side note, I'm running Ubuntu 18.04 which has cmake version 3.10 through apt. I had to install the latest version through the cmake website which wasn't a big deal. However, for the sake of ease, you might want to stick with 3.10 just so that the most up to date version on apt is supported.
Thank you for your time and effort!
