### ISSUE TITLE
Adding Support for Spheres and Cylinders

### ISSUE THREAD

**Issue by Michael-Equi** [MattiaMontanari/openGJK#18]
I am working on an application that requires being able to check for collisions between polyhedra and spheres/cylinders. I am currently figuring out how to create a bounding polyhedron for these shapes as a temporary way to use this algorithm with them but I am curious as to how hard it would be to add native support for those shapes to this GJK implementation. I have worked with basic implementations of GJK in the past  and implementing spheres/cylinders mostly came down to adding support functions for them. It does not look like it would be that easy in this implementation but might it still be worth looking into adding?

Thanks for the library btw, works well and has saved me so much time!

**Comment by MattiaMontanari** [comment]
Yes you're right, it won't be that easy. Realistically I can't commit to create that, but I can help you or you may want to try other libraries that support spheres and cylinders. If you don't have time tho, you may just create a cloud of points to mimic sphere and cylinders and pass those to this library. Depends on what you need to do and the time you have :)

**Comment by Michael-Equi** [comment]
Its not super high on my priority list so I may just look into creating a bounding convex polyhedron with a bunch of points. Do you know of a good way of doing that?

**Comment by MattiaMontanari** [comment]
You can look at Matlab sphere and cylinder commands ;) The function source
may be also available
