### ISSUE TITLE
Attempted to write a file into source

### ISSUE THREAD

**Issue by VollmerMarcel** [MattiaMontanari/openGJK#19]
When executing `cmake .` on ubuntu 18.04.5 I get the error:

`CMake Error at /usr/share/cmake-3.21/Modules/FindOpenMP.cmake:184 (file):
  file attempted to write a file:
  .../openGJK/CMakeFiles/FindOpenMP/OpenMPTryFlag.c into a source
  directory.

Call Stack (most recent call first):
  /usr/share/cmake-3.21/Modules/FindOpenMP.cmake:200 (_OPENMP_WRITE_SOURCE_FILE)
  /usr/share/cmake-3.21/Modules/FindOpenMP.cmake:461 (_OPENMP_GET_FLAGS)
  CMakeLists.txt:71 (find_package)
`

I traced this back to an issue with the setting `set(CMAKE_DISABLE_SOURCE_CHANGES ON)` in  `.../openGJK/cmake/CMakeDefaults.cmake` setting it to OFF instead worked.

**Comment by MattiaMontanari** [comment]
I removed openmp altogether
