### ISSUE TITLE
Error Using mex - Matlab under Linux

### ISSUE THREAD

**Issue by Amir-Zargar** [MattiaMontanari/openGJK#33]
On Ubuntu 20.04.4 LTS and with gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1~20.04).

>> mex(fullfile('openGJK.c'),...  % Source of openGJK 
    '-largeArrayDims', ...      % Support large arrays
    optflug, ...                % Compiler flag for debug/optimisation
    fullfile('-I','/home/amir/MATLAB/Gabriel/OpenGJK_Master/include'),...      % Folder to header files
    '-outdir', pwd,...          % Ouput directory for writing mex function
    '-output', 'openGJK',...    % Name of ouput mex file
    '-DMATLAB_MEX_BUILD',...  % Define variable for mex function in source files
    silflag )                   % Silent/verbose flag
/home/amir/MATLAB/Gabriel/OpenGJK_Master/openGJK.c: In function ‘mexFunction’:
/home/amir/MATLAB/Gabriel/OpenGJK_Master/openGJK.c:733:13: warning: implicit declaration of function ‘mxCreategkFloatMatrix’; did you mean ‘mxCreateStructMatrix’? [-Wimplicit-function-declaration]
  733 |   plhs[0] = mxCreategkFloatMatrix(1, 1, mxREAL);
      |             ^~~~~~~~~~~~~~~~~~~~~
      |             mxCreateStructMatrix
/home/amir/MATLAB/Gabriel/OpenGJK_Master/openGJK.c:733:11: warning: assignment to ‘mxArray *’ {aka ‘struct mxArray_tag *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  733 |   plhs[0] = mxCreategkFloatMatrix(1, 1, mxREAL);
      |           ^
/home/amir/MATLAB/Gabriel/OpenGJK_Master/openGJK.c:766:17: warning: implicit declaration of function ‘gjk’ [-Wimplicit-function-declaration]
  766 |   distance[0] = gjk(bd1, bd2, &s);
      |                 ^~~

Error using mex
/usr/bin/ld: /tmp/mex_1491118059826_3560/openGJK.o: in function `mexFunction':
openGJK.c:(.text+0x3464): undefined reference to `mxCreategkFloatMatrix'
/usr/bin/ld: openGJK.c:(.text+0x355d): undefined reference to `gjk'
collect2: error: ld returned 1 exit status

**Comment by MattiaMontanari** [comment]
@Amir-Zargar please clone the branch in #34 and let me know if it works. Thanks

**Comment by Amir-Zargar** [comment]
Hi,

I downloaded new codes and run it again which gave me the same error, as I posted in GitLab.

Thank you,
Amir

**Comment by Amir-Zargar** [comment]
Thank you, problem solved. I have my mex file running on Matlab under Linux.
