### ISSUE TITLE
Go implementation

### ISSUE THREAD

**Issue by aturkenov** [MattiaMontanari/openGJK#38]
Hello! @MattiaMontanari
Can i add go implementation of openGJK to examples folder? Go module uses c api.

**Comment by MattiaMontanari** [comment]
> Hello! @MattiaMontanari
> 
> Can i add go implementation of openGJK to examples folder? Go module uses c api.
> 
> 
> 
> 

Absolutely! Should be very simple, let me know if I can help.

**Comment by aturkenov** [comment]
Hello, @MattiaMontanari
I've implemented example, can you read https://github.com/MattiaMontanari/openGJK/pull/39.

**Comment by MattiaMontanari** [comment]
Thank you @aturkenov! I have finally merged your contribution and created a pipeline for it
