### ISSUE TITLE
How to judge if two bodies penetrate each other or not ?

### ISSUE THREAD

**Issue by wangxi0706** [MattiaMontanari/openGJK#43]
Thanks for the code! Neat and elegant.

Since the returned distance is always >=0, how can we judge if they penetrate? Using d > 1e-15 or other tolerances?

**Comment by MattiaMontanari** [comment]
@wangxi0706 That's right. 1e-15 is very small however. Set a larger number and compare it to what you get with 1e-15. 
Set this tolerance large enough, but not too large. 1e-8 may be enough. If you get similar results to 1e-15 then you'll be good to go.

Overall, It depends on the algorithm you use after GJK: Are you using EPA?

**Comment by MattiaMontanari** [comment]
@wangxi0706 feel free to reopen the issue if you have more questions
