### ISSUE TITLE
How to resolve the issue of UNEXPECTED VALUES!!!

### ISSUE THREAD

**Issue by wangxi0706** [MattiaMontanari/openGJK#45]
I am trying to compute the distance between blocks in the following figure, and it prints UNEXPECTED VALUES!!!  What is the possible reason for that? Can I leave it alone?

![image](https://github.com/MattiaMontanari/openGJK/assets/37179881/913a34c7-ed6c-49fe-85da-f3d2c7020f85)

**Comment by MattiaMontanari** [comment]
@wangxi0706 so sorry for the late reply. You may have discovered a nice bug! Can you please send me the coordinates of all nodes of both objects when this occurs?

**Comment by MattiaMontanari** [comment]
@wangxi0706  please reopen the bug if you can help me reproducing it
