### ISSUE TITLE
Incorrect distance calculation between overlapping polyhedrons returns non-zero value

### ISSUE THREAD

**Issue by HanJaeJoon** [MattiaMontanari/openGJK#52]
First of all, thank you for this amazing library. It has been incredibly useful for my project. 😊

When calculating the distance between two overlapping polyhedrons, the library returns a non-zero value instead of `0`.
This seems to indicate a floating point precision problem in the distance calculation logic.

![image](https://github.com/user-attachments/assets/139011a8-93e8-41f0-a108-f1d81443fce7)

### Code Examples
Program.cs
``` c#
var ia = new float[3, 8] {
    { 90945.08f, 91077.46f, 91454.92f, 91322.54f, 90945.08f, 91077.46f, 91454.92f, 91322.54f },
    { 54122.54f, 53745.082f, 53877.46f, 54254.918f, 54122.54f, 53745.082f, 53877.46f, 54254.918f },
    { 300f, 300f, 300f, 300f, 0f, 0f, 0f, 0f, },
};

var ib = new float[3, 8] {
    { 90919.64f, 91162.62f, 91480.36f, 91237.38f, 90919.64f, 91162.62f, 91480.36f, 91237.38f },
    { 54037.383f, 53719.637f, 53962.617f, 54280.363f, 54037.383f, 53719.637f, 53962.617f, 54280.363f },
    { 300f, 300f, 300f, 300f, 0f, 0f, 0f, 0f, },
};

var distance = ComputeDistance(ia.GetLength(1), ia, ib.GetLength(1), ib);

Console.WriteLine(distance); // 0.0032915156

[DllImport("Libs/libopengjk_ce.dll", EntryPoint = "csFunction",
        CallingConvention = CallingConvention.StdCall,
        CharSet = CharSet.Ansi,
        BestFitMapping = false,
        ThrowOnUnmappableChar = true)]
static extern float ComputeDistance(int na, float[,] ia, int nb, float[,] ib);
```

### Expected Behavior
When the polyhedrons overlap, the distance calculation should return 0 as the minimum distance.

### Actual Behavior
The library returns a non-zero value (in my case 0.0032915156) for overlapping polyhedrons.

### Additional Information
To work around this issue temporarily, I applied a tolerance of `1e-2f` to the distance calculation, treating any result smaller than this value as 0. This approach seems to resolve the problem in my case.

However, I am unsure if `1e-2f` is an appropriate or recommended value for this library.

Is `1e-2f` a reasonable tolerance for handling floating-point precision issues in this context?
Would you recommend a different value, or is there a library-standard epsilon that should be used?

**Comment by MattiaMontanari** [comment]
Thanks for the detailed report and apologies for the late reply.

This case is prune to round-off error and you have find the solution that works best for your application. Here is what I would do:

1. Apply a large tolerance - like you did. Start with `5e-3f`. I'd increment gradually and test before jumping to the next order of magnitude. The problem with a large tolerance here is that it may affects the quality of the game/app you're working on. 
2.  If that's the large tolerance does affect the behaviour of your game/app, you have to edit opengjk.c at line 46-47 the values of
```
#define eps_rel22        (gkFloat) gkEpsilon * 1e4f
#define eps_tot22        (gkFloat) gkEpsilon * 1e2f
```
gradually increase the multiplication factors. Try 5e4f and 2e2f, and increase untile you find a good compromise. You're editing C, so you have to recompile the code.

**Comment by HanJaeJoon** [comment]
Thank you for your response.
