### ISSUE TITLE
How to use this for 2D case?

### ISSUE THREAD

**Issue by Fengyixin-research** [MattiaMontanari/openGJK#53]
Thanks for your open source code. I just want to use it for my 2D polygons in matlab. However, the examples are 3D cases, is there anyway to use it in 2D cases?

**Comment by MattiaMontanari** [comment]
you've got two options: rewrite the whole code, or just add 0 as third coordinate :) 
Your 2D polygons will have X, Y coordinates, just set the Z coordinate of all points to 0 and you can use opengjk.

**Comment by Fengyixin-research** [comment]
Thanks for your quick reply. By the way, I'm not familiar with using C codes in Matlab. Do I need to compile C codes to mex or library file? Is there any comprehensive instruction? Thank you.

**Comment by Fengyixin-research** [comment]
I finally got it. Just type the instruction sentences in cmd. Then a mex file will be generated. I can directly use it for computation. Thanks!
