### ISSUE TITLE
Installation script for Linux installing openGJK to /usr/local

### ISSUE THREAD

**Issue by jorgensd** [MattiaMontanari/openGJK#7]
To be able to trying to integrate a prototype of FEniCSx with openGJK, it would be beneficial to have an install-script that does not require copy-paste of headers, and that the include files are stored somewhere central, like /usr/local.

**Comment by MattiaMontanari** [comment]
would this be ok?
```
install(TARGETS test DESTINATION /usr/local/lib/opengjk)
install(FILES opengjk.h DESTINATION /usr/local/lib/opengjk/include)
```
